name: CI/CD to Cloud Storage

on:
  push:
    branches:
       - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: <your-project-id>
        export_default_credentials: true

    - name: Deploy to Cloud Storage
      run: |
        gsutil cp -r ./* gs://my_bucket_dataproc/dataprocessing/
        
