name: CI/CD Pipeline to Cloud Storage

on:
  push:
    branches:
       - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
#    - name: Print Service Account Info
#     run: |
#       echo "Service Account: $GS_SA_KEY"
#       gcloud auth login cicd-pipeline-service-account@root-rock-413418.iam.gserviceaccount.com
 #      gcloud auth list
  #     gcloud projects list
   #    gcloud config list
    #   env:
     #   GCP_SA_KEY: ${{ secrets.GS_SA_KEY }}
    - name: Authenticate Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
         credentials_json: ${{ secrets.GS_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
       service_account_email: ${{ secrets.GS_SERVICE_ACCOUNT_EMAIL }}
       service_account_key: ${{ secrets.GS_SA_KEY }}
       export_default_credentials: true
       skip_install: false
       version: ">= 363.0.0"
    - name: GitHub Action for pytest
  # You may pin to the exact commit or the version.
  # uses: cclauss/GitHub-Action-for-pytest@5863d02de95f37516a732802fa6257dfdf93e54c
      uses: cclauss/GitHub-Action-for-pytest@0.5.0   
    - name: Deploy to Cloud Storage
      run: |
        gsutil cp -r ./* gs://my_bucket_dataproc/dataprocessing/
        gcloud auth list
        gcloud projects list
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GS_SA_KEY }}

  my_job:
    runs-on: ubuntu-18.04

    steps:
      - name: Python Coverage
        # You may pin to the exact commit or the version.
        # uses: orgoro/coverage@4e3bc9302f715595336a40f7dd4a3b15c687bdb4
        uses: orgoro/coverage@v3.1
        with:
          # Local path to a coverage xml file like the output of pytest --cov
          coverageFile: ${{ secrets.COVERAGE_FILE }}
          # GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}
          # The coverage threshold for average over all files [0,1]
          thresholdAll: # optional, default is 0.0
          # The coverage threshold for average over new files [0,1]
          thresholdNew: # optional, default is 0.0
          # The coverage threshold for average over modified files [0,1]
          thresholdModified: # optional, default is 0.0

    - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ${{ env.COVERAGE_FILE }}

      # Comment on the pull request with coverage report
      - name: Comment on pull request with coverage report
        uses: unsplash/comment-on-pr@v1
        with:
          msg: |
            Coverage Report:
            ![Coverage Report](https://github.com/${{ github.repository }}/raw/main/${{ env.COVERAGE_FILE }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
        
