name: CI/CD to Cloud Storage

on:
  push:
    branches:
       - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
#    - name: Print Service Account Info
#     run: |
#       echo "Service Account: $GS_SA_KEY"
#       gcloud auth login cicd-pipeline-service-account@root-rock-413418.iam.gserviceaccount.com
 #      gcloud auth list
  #     gcloud projects list
   #    gcloud config list
    #   env:
     #   GCP_SA_KEY: ${{ secrets.GS_SA_KEY }}
        
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GS_SA_KEY }}
        project_id: root-rock-413418
        export_default_credentials: true

    - name: Deploy to Cloud Storage
      run: |
        gsutil cp -r ./* gs://my_bucket_dataproc/dataprocessing/
        
