name: CI/CD Pipeline to Cloud Storage

on:
  push:
    branches:
       - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
#    - name: Print Service Account Info
#     run: |
#       echo "Service Account: $GS_SA_KEY"
#       gcloud auth login cicd-pipeline-service-account@root-rock-413418.iam.gserviceaccount.com
 #      gcloud auth list
  #     gcloud projects list
   #    gcloud config list
    #   env:
     #   GCP_SA_KEY: ${{ secrets.GS_SA_KEY }}
    - name: Authenticate Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
         credentials_json: ${{ secrets.GS_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
       service_account_email: ${{ secrets.GS_SERVICE_ACCOUNT_EMAIL }}
       service_account_key: ${{ secrets.GS_SA_KEY }}
       export_default_credentials: true
       skip_install: false
       version: ">= 363.0.0"
    - name: GitHub Action for pytest
  # You may pin to the exact commit or the version.
  # uses: cclauss/GitHub-Action-for-pytest@5863d02de95f37516a732802fa6257dfdf93e54c
      uses: cclauss/GitHub-Action-for-pytest@0.5.0   
    - name: Deploy to Cloud Storage
      run: |
        gsutil cp -r ./* gs://my_bucket_dataproc/dataprocessing/
        gcloud auth list
        gcloud projects list
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GS_SA_KEY }}
      
        
