---
name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 363.0.0"
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info
      - name: Terraform Init
        run: |
          terraform init
        working-directory: terraform
      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        working-directory: terraform
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve 
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        working-directory: terraform
      - name: Setup Cluster
        run: |
          echo "Cluster setup completed!"
  cleanup:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Terraform Init
        run: |
          terraform init
        working-directory: terraform
      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        working-directory: terraform
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: terraform

