name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
    
      - name: Install Google Cloud SDK
        run: |
            curl https://sdk.cloud.google.com | bash
            export PATH=$PATH:/home/runner/google-cloud-sdk/bin
            gcloud components install google-cloud-sdk-app-engine-python-extras google-cloud-sdk-bigtable-emulator google-cloud-sdk-spanner-migration-tool google-cloud-sdk-firestore-emulator kubectl google-cloud-sdk-package-go-module google-cloud-sdk-config-connector google-cloud-sdk-app-engine-grpc google-cloud-sdk-app-engine-java google-cloud-sdk-kpt google-cloud-sdk-nomos google-cloud-sdk-anthos-auth google-cloud-sdk-app-engine-python google-cloud-sdk-istioctl google-cloud-sdk-harbourbridge google-cloud-sdk-gke-gcloud-auth-plugin google-cloud-sdk-enterprise-certificate-proxy google-cloud-sdk-local-extract google-cloud-sdk-datastore-emulator google-cloud-sdk-log-streaming google-cloud-sdk-kubectl-oidc google-cloud-sdk-cloud-run-proxy google-cloud-sdk-minikube google-cloud-sdk-pubsub-emulator google-cloud-cli-docker-credential-gcr google-cloud-sdk-cloud-build-local google-cloud-sdk-terraform-tools google-cloud-sdk-cbt google-cloud-sdk-spanner-emulator google-cloud-sdk-app-engine-go google-cloud-sdk-skaffold
          
      - name: Update gcloud components
        run: gcloud components update
     
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve 
