name: Python Coverage

on:
  pull:
    branches:
      - master

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Python Coverage
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: ${{ secrets.COVERAGE_FILE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.0
          thresholdNew: 0.0
          thresholdModified: 0.0

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ${{ secrets.COVERAGE_FILE }}



      - name: Comment on pull request with coverage report
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"body": "Coverage Report: ![Coverage Report](https://github.com/${{ github.repository }}/raw/main/${{ env.COVERAGE_FILE }})"}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"     
