# File: .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Python files
        run: |
          pip install pylint
          pylint ./**/*.py

